name: zpi

on:
  push:
    branches: [ "*" ]
    tags:
      - "v*.*.*"
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Chmod
        run: chmod +x ./zpi.sh ./scripts/*.sh
      - name: Check ZPI
        run: shellcheck ./zpi.sh
      - name: Check Scripts
        run: shellcheck ./scripts/*.sh
      - name: Init
        run: ./zpi.sh init
      - name: Build
        run: ./zpi.sh build
      - name: Release
        uses: softprops/action-gh-release@v1

        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            ./build/**/*.img
            ./build/**/*.swu
